const CACHE_NAME = 'animanga-v2';
const DYNAMIC_CACHE = 'animanga-dynamic-v2';

// In a build environment (Vite), files like index.tsx are bundled into hashed JS files.
// We cannot hardcode them here easily without a plugin. 
// We will cache the App Shell (HTML & Manifest) and rely on runtime caching for assets.
const PRECACHE_URLS = [
  '/',
  '/index.html',
  '/manifest.json'
];

// Domains to cache (CDNs)
const EXTERNAL_DOMAINS = [
  'cdn.tailwindcss.com',
  'fonts.googleapis.com',
  'fonts.gstatic.com',
  'picsum.photos', // Mock images
  'cdn-icons-png.flaticon.com' // Icons
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheName !== CACHE_NAME && cacheName !== DYNAMIC_CACHE) {
            return caches.delete(cacheName);
          }
        })
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Strategy 1: Cache First for External Assets
  if (EXTERNAL_DOMAINS.some(domain => url.hostname.includes(domain))) {
    event.respondWith(
      caches.match(event.request).then((cachedResponse) => {
        if (cachedResponse) return cachedResponse;
        return fetch(event.request).then((response) => {
          if (!response || response.status !== 200 || response.type !== 'basic' && response.type !== 'cors' && response.type !== 'opaque') {
            return response;
          }
          const responseToCache = response.clone();
          caches.open(DYNAMIC_CACHE).then((cache) => {
            cache.put(event.request, responseToCache);
          });
          return response;
        });
      })
    );
    return;
  }

  // Strategy 2: Stale-While-Revalidate for App Files
  // This will catch the hashed JS/CSS files generated by Vite
  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      const fetchPromise = fetch(event.request).then((networkResponse) => {
        if (networkResponse && networkResponse.status === 200) {
          const responseToCache = networkResponse.clone();
          // Decide which cache to use based on URL or file type
          // For simplicity, we put everything else in dynamic cache or main cache
          caches.open(CACHE_NAME).then((cache) => {
            cache.put(event.request, responseToCache);
          });
        }
        return networkResponse;
      }).catch(() => {
        // Network failed return cached
        return cachedResponse;
      });

      return cachedResponse || fetchPromise;
    })
  );
});